(()=>{'use strict';
const E=window.ArenaEngine;if(!E)return;const P=E.prototype;
const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const keys=e=>Object.keys(e.houses||{});
const flags=(e,h)=>e.houses[h].roundFlags||(e.houses[h].roundFlags={});
const capital=(e,h)=>e.data.map.capitals[h];
function attackInfluenceCost(e,h,other){const f=flags(e,h),seen=f.conflictHouses||[];if(h==='Ортайн'&&!seen.includes(other))return 1;if(h==='Эркай'&&!seen.includes(other)&&seen.length>=1)return 1;return 0}
function noteConflict(e,h,other){const f=flags(e,h);f.conflictHouses??=[];if(!f.conflictHouses.includes(other))f.conflictHouses.push(other)}
function planForAction(a){if(!a?.target)return null;if(a.target.recaptureCapital||a.target.recaptureHome)return'RECAPTURE';if(a.target.isEnemyCapital)return'CAPITAL_ATTACK';if(a.target.completesIsland)return'ISLAND_COMPLETION';if(a.target.firstCenterHalf)return'CENTER_CAPTURE';return null}
function targetValue(e,h,id){const t=e.territories[id],w=e.data.aiConfig?.canonical_target_scoring||{};if(!t)return 0;const owner=t.owner;let v=owner&&owner!==h?n(w.enemy_base,5):!owner?n(w.neutral_base,6):0;v+=n(e.targetIncomeValue?.(id,h));if(!owner)v-=n(t.resistance);if(e.homeHouseFor?.(id)===h&&owner!==h)v+=id===capital(e,h)?n(w.recapture_capital_bonus,12):n(w.recapture_home_bonus,6);if(e.completesIsland?.(h,id))v+=n(w.complete_island_bonus,9);if(id.startsWith('S')&&!e.controlsAnyIslandHalf?.(h))v+=n(w.first_center_half_bonus,4);if(Object.entries(e.data.map.capitals||{}).some(([x,c])=>x!==h&&c===id))v+=n(w.enemy_capital_bonus,10);return Math.max(0,v)}
function accessUtility(e,h,other){let best=0,plan=null;for(const src of e.ownedUnitLocations(h)){for(const mid of e.land[src]||[]){if(e.territories[mid]?.owner!==other)continue;for(const dest of e.land[mid]||[]){const t=e.territories[dest];if(!t||t.owner===h||t.owner===other)continue;const v=targetValue(e,h,dest);if(v>best){best=v;plan=planForAction({target:{recaptureHome:e.homeHouseFor?.(dest)===h&&t.owner!==h,recaptureCapital:capital(e,h)===dest&&t.owner!==h,isEnemyCapital:Object.entries(e.data.map.capitals||{}).some(([x,c])=>x!==h&&c===dest),completesIsland:e.completesIsland?.(h,dest),firstCenterHalf:dest.startsWith('S')&&!e.controlsAnyIslandHalf?.(h)}})}}}}return{score:best,plan}}
function sayrvenCost(e,h,base){const f=flags(e,h);if(h==='Сайрвен'&&base>=3&&!f.sayrvenPurchaseDiscountUsed){f.sayrvenPurchaseDiscountUsed=true;return Math.max(1,base-1)}return base}
const _start=P.startRound;P.startRound=function(){const out=_start.call(this);for(const h of keys(this)){const f=flags(this,h);f.conflictHouses=[];f.sayrvenPurchaseDiscountUsed=false;f.varSecondAttackBonusUsed=false;f.erkaiDefenseBonusUsed=false;f.airelDynastyDiscountUsed=false}return out};
const _begin=P.beginOwnAction;P.beginOwnAction=function(h){const out=_begin.call(this,h);for(const c of this.allCharacters(h)){if(c?.young&&c.mode==='АРМИЯ'){c.mode='ДВОР';c.armyLocation=null}}if(!this.commanderAt(h,capital(this,h))){const c=this.allCharacters(h).filter(x=>x.alive&&!x.young&&x.health==='Здоров'&&x.mode==='ДВОР'&&(x.type==='Правитель'||x.type==='Законный ребёнок')).sort((a,b)=>(n(b.attack)+n(b.defense))-(n(a.attack)+n(a.defense)))[0];if(c&&n(this.territories[capital(this,h)]?.units[h])>0&&this.allCharacters(h).filter(x=>x.alive&&x.mode==='АРМИЯ').length<2){c.mode='АРМИЯ';c.armyLocation=capital(this,h);this.log('commander',`${h}: ${c.name} назначен командиром`,{house:h,character:c.uid,location:c.armyLocation})}}return out};
P.assignCommander=function(h,uid,loc=capital(this,h)){const c=this.characterByUid(h,uid);if(!c?.alive||c.young||c.health!=='Здоров'||c.mode!=='ДВОР'||this.houses[h].regency)return{valid:false};if(loc!==capital(this,h)||n(this.territories[loc]?.units[h])<=0||this.commanderAt(h,loc)||this.allCharacters(h).filter(x=>x.alive&&x.mode==='АРМИЯ').length>=2)return{valid:false};c.mode='АРМИЯ';c.armyLocation=loc;this.log('commander',`${h}: ${c.name} назначен командиром`,{house:h,character:uid,location:loc});return{valid:true}};
P.commanderEntries=function(h){const cap=capital(this,h),hs=this.houses[h],inArmy=this.allCharacters(h).filter(c=>c.alive&&c.mode==='АРМИЯ').length,capitalOccupied=Boolean(this.commanderAt(h,cap)),hasArmy=n(this.territories[cap]?.units[h])>0;return this.allCharacters(h).filter(c=>c.alive&&c.health!=='Мёртв').map(c=>({uid:c.uid,name:c.name,mode:c.mode,armyLocation:c.armyLocation,canAssign:!c.young&&c.health==='Здоров'&&c.mode==='ДВОР'&&!hs.regency&&hasArmy&&!capitalOccupied&&inArmy<2,canReturn:c.mode==='АРМИЯ'&&c.armyLocation===cap}))};
const _income=P.incomePhase;P.incomePhase=function(){const out=_income.call(this);for(const h of keys(this)){const r=this.houses[h].ruler;if(r?.alive&&r.mode==='ДВОР'&&n(r.management)>=2){this.houses[h].gold++;this.log('income',`${h}: +1 золото — Управление 2 правителя при Дворе`,{house:h,gold:1,source:'MANAGEMENT_2_RULER'})}}return out};
P.doRecruit=function(h,a){const extra=n(this.stateFlags.recruitExtraCost),base=n(a.amount)+extra,cost=sayrvenCost(this,h,base);if(!this.spendGold(h,cost,'Найм'))throw new Error('Recruit cost became illegal');this.territories[capital(this,h)].units[h]=n(this.territories[capital(this,h)].units[h])+n(a.amount)};
P.doFort=function(h,a){const t=this.territories[a.territory],base=3,cost=sayrvenCost(this,h,base);if(!t||t.owner!==h||Object.values(this.data.map.capitals).includes(t.id)||t.fort||this.houses[h].fortsBuilt>=2||!this.spendGold(h,cost,'Крепость'))throw new Error('Fort became illegal');t.fort=true;t.fortOwner=h;this.houses[h].fortsBuilt++;this.metrics.total.fortsBuilt++};
P.doAdviser=function(h,a){const base=n(a.cost,2),cost=sayrvenCost(this,h,base);if(!this.spendGold(h,cost,'Советник'))throw new Error('Adviser cost illegal');const row=(this.data.advisors||[]).find(x=>String(x['Тип'])===String(a.adviserType));if(row)this.houses[h].advisers.push(JSON.parse(JSON.stringify(row)))};
const _relation=P.doRelation;P.doRelation=function(h,a,kind){if(kind!=='Официальный Пакт')return _relation.call(this,h,a,kind);const other=a.other,hs=this.houses[h],oh=this.houses[other];let ch=Math.max(0,1-n(this.stateFlags.pactDiscount)),co=1;if(h==='Ортайн'&&!hs.ortaynFreePactUsed)ch=0;if(other==='Ортайн'&&!oh.ortaynFreePactUsed)co=0;if(hs.influence<ch||oh.influence<co)throw new Error('Pact influence became illegal');if(ch)this.spendInfluence(h,ch,kind);if(co)this.spendInfluence(other,co,kind);oh.reserved++;this.relationships.push({id:`${kind}:${h}:${other}:${this.round}:${this.actionTotal}`,kind,a:h,b:other,active:true,createdRound:this.round,fullRounds:0,rewarded:{[h]:false,[other]:false}});this.metrics.total.pacts++;if(h==='Ортайн')hs.ortaynFreePactUsed=true;if(other==='Ортайн')oh.ortaynFreePactUsed=true;for(const x of [h,other])if(x==='Тасвар'&&!this.houses[x].tasvarPactInfluenceUsed){this.houses[x].tasvarPactInfluenceUsed=true;this.houses[x].influence++;this.log('resource','Тасвар: +1 Влияние после нового Официального Пакта',{house:'Тасвар',source:'HOUSE_ABILITY'})}this.log('diplomacy',`${h} и ${other}: Официальный Пакт заключён`,{house:h,other,result:'accepted'})};
const _legit=P.doLegit;P.doLegit=function(h,a){if(h!=='Айрель'||flags(this,h).airelDynastyDiscountUsed)return _legit.call(this,h,a);const hs=this.houses[h],c=hs.knownBastards.find(x=>x.alive&&!hs.legitimizedBastards.some(y=>y.uid===x.uid));if(!c||!this.spendInfluence(h,2,'Легитимизация (Айрель -1)'))throw new Error('Legitimization became illegal');flags(this,h).airelDynastyDiscountUsed=true;hs.legitimizedBastards.push(c);hs.dynastyActions.add('легитимизация');if(!hs.achievements.legitimized){hs.score++;hs.achievements.legitimized=true;this.log('vp',`${h}: +1 ОП — легитимизирован бастард`,{house:h})}return{valid:true}};
const _divorce=P.doDivorce;P.doDivorce=function(h,a){if(h!=='Айрель'||flags(this,h).airelDynastyDiscountUsed)return _divorce.call(this,h,a);const r=this.relationships.find(x=>x.id===a.relationId&&x.active&&x.kind==='Династический союз'&&(x.a===h||x.b===h));if(!r||!this.spendInfluence(h,2,'Развод (Айрель -1)'))throw new Error('Divorce became illegal');flags(this,h).airelDynastyDiscountUsed=true;r.active=false;r.endedReason='divorce';r.endedRound=this.round;for(const uid of r.characters||[])for(const house of keys(this)){const c=this.characterByUid(house,uid);if(c)c.spouseOf=null}this.log('diplomacy',`${h}: развод; союз прекращён`,{house:h,relation:r.id});return{valid:true}};
const _disease=P.resolveDisease;P.resolveDisease=function(h,c,mod){const f=flags(this,h);let m=n(mod);if(h==='Айрель'&&!f.airelDiseasePenaltyUsed){f.airelDiseasePenaltyUsed=true;m-=1}return _disease.call(this,h,c,m)};
const _resolve=P.resolvePvp;P.resolvePvp=function(att,def,a,raid){const cost=attackInfluenceCost(this,att,def);if(cost&&!this.spendInfluence(att,cost,att==='Ортайн'?'Первый конфликт раунда':'Атака второго Дома в раунде'))throw new Error('House attack influence cost became illegal');noteConflict(this,att,def);noteConflict(this,def,att);const ac=this.commanderAt(att,a.source),dc=this.commanderAt(def,a.dest),af=flags(this,att),df=flags(this,def);let aa=0,dd=0;if(att==='Варкайр'&&ac&&this.houses[att].ruler&&ac.uid===this.houses[att].ruler.uid){aa=1+(af.varSecondAttackBonusUsed?0:1);af.varSecondAttackBonusUsed=true;ac.attack=n(ac.attack)+aa}if(def==='Эркай'&&dc&&this.houses[def].ruler&&dc.uid===this.houses[def].ruler.uid&&(a.dest===capital(this,def)||this.territories[a.dest]?.fort)&&!df.erkaiDefenseBonusUsed){dd=1;df.erkaiDefenseBonusUsed=true;dc.defense=n(dc.defense)+1}try{return _resolve.call(this,att,def,a,raid)}finally{if(aa&&ac)ac.attack-=aa;if(dd&&dc)dc.defense-=dd}};
const _free=P.freeProcedures;P.freeProcedures=function(h){return _free.call(this,h).map(p=>p.type==='break'?{...p,cost:n(p.cost)+n(this.stateFlags.breakExtraInfluence)}:p)};
const _legal=P.legalActions;P.legalActions=function(h){let out=_legal.call(this,h);out=out.filter(a=>{if(!['march','raid'].includes(a.type))return true;const o=this.territories[a.dest]?.owner;return !o||o===h||this.houses[h].influence>=attackInfluenceCost(this,h,o)});for(const a of out){const p=planForAction(a);if(p){a.planId=p;a.planMatch=true}if(a.type==='access'){const u=accessUtility(this,h,a.other);if(u.score>0){a.scoreComponents={...(a.scoreComponents||{}),accessRoute:u.score};if(u.plan){a.planId=u.plan;a.planMatch=true}}}}return out};
if(window.ArenaHouseAgent){const _decide=window.ArenaHouseAgent.prototype.decide;window.ArenaHouseAgent.prototype.decide=function(ctx={}){if(!ctx.activePlan){const ps=(ctx.legalActions||[]).map(a=>a.planId).filter(Boolean),priority=['RECAPTURE','CAPITAL_ATTACK','ISLAND_COMPLETION','CENTER_CAPTURE','PORT_PREPARATION'];ctx={...ctx,activePlan:priority.find(p=>ps.includes(p))||null}}return _decide.call(this,ctx)}}
const _cap=P.capabilityReport;P.capabilityReport=function(){const x=_cap.call(this);if(!x.implementedNormalActions.includes('ACT-PACT'))x.implementedNormalActions.splice(4,0,'ACT-PACT');x.humanControl=true;x.humanCommanderManagement=true;x.uiPanels=['MAP','HOUSES','DIPLOMACY','JOURNAL','GAME_MASTER'];return x};
P.setController=function(h,mode='AI'){this.controllers??={};if(this.houses[h])this.controllers[h]=mode==='HUMAN'?'HUMAN':'AI';return this.controllers[h]};
P.controllerResolver=function(h){return this.controllers?.[h]||'AI'};
const _capture=P.captureCharacter;P.captureCharacter=function(owner,c,captor,location){if(this.controllerResolver(captor)!=='HUMAN')return _capture.call(this,owner,c,captor,location);c.alive=true;c.mode='ПЛЕН';c.heldBy=captor;c.armyLocation=null;c.captiveLocation=location;c.ransomOffer=null;c.ransomResponse=null;this.metrics.total.prisonerCaptures++;this.logPrisoner('capture',owner,c,captor,{location,detail:`${c.name} (${owner}) попал в плен к ${captor}`});this.pendingPrisoner={owner,uid:c.uid,captor,location};return{valid:true,pending:true}};
P.currentPrisonerPrompt=function(){if(!this.pendingPrisoner)return null;const r=this.pendingPrisoner,c=this.characterByUid(r.owner,r.uid);return{...r,name:c?.name,choices:['release','hold','ransom','execute'],detentionLocations:this.nearestDetentionLocations(r.captor,r.location)}};
P.submitPrisonerChoice=function(choice,amount=null,response=null,detentionChoice=null){if(!this.pendingPrisoner)return{valid:false,detail:'Нет ожидающего решения'};const r=this.pendingPrisoner,out=this.resolvePrisonerDecision(r,choice,amount,response,detentionChoice);if(out?.valid)this.pendingPrisoner=null;return out};
const _step=P.step;P.step=function(actionId=null){if(this.pendingPrisoner)return this.exportData();return _step.call(this,actionId)};
window.ARENA_V572_CURRENT_PATCH={currentParity:true,houseRules:true,strategicPlans:true,humanPrisonerChoice:true};
})();
