ArenaEngine.prototype.legalActions=function(h){
 const a=_legalActions.call(this,h),hs=this.houses[h];
 if(!hs)return a;
 if(this.totalTerritories(h)===0){return a.filter(x=>!['march','recruit','fort'].includes(x.type)).concat(hs.gold>=3?[{id:'RETURN',type:'return',label:'Возвращение из Изгнания',baseScore:20,legal:true}]:[])}
 if(hs.knownBastards.some(c=>c.alive&&!hs.legitimizedBastards.some(x=>x.uid===c.uid))&&hs.influence>=3)a.push({id:'LEGIT',type:'legit',label:'Легитимизировать бастарда',baseScore:5,legal:true});
 for(const r of this.relationships.filter(r=>r.active&&r.kind==='Династический союз'&&(r.a===h||r.b===h)))if(hs.influence>=3)a.push({id:`DIVORCE:${r.id}`,type:'divorce',label:`Развод: ${r.a===h?r.b:r.a}`,relationId:r.id,baseScore:-1,legal:true});
 return a
};
const _applyAction=ArenaEngine.prototype.applyAction;
ArenaEngine.prototype.applyAction=function(h,a){if(a.type==='legit')return this.doLegit(h,a);if(a.type==='divorce')return this.doDivorce(h,a);if(a.type==='return')return this.doReturn(h,a);return _applyAction.call(this,h,a)};
ArenaEngine.prototype.doLegit=function(h,a){const hs=this.houses[h],c=hs.knownBastards.find(c=>c.alive&&!hs.legitimizedBastards.some(x=>x.uid===c.uid));if(!c||!this.spendInfluence(h,3,'Легитимизация'))throw new Error('Legitimization became illegal');hs.legitimizedBastards.push(c);hs.dynastyActions.add('легитимизация');if(!hs.achievements.legitimized){hs.score+=1;hs.achievements.legitimized=true;this.log('vp',`${h}: +1 ОП — легитимизирован бастард`,{house:h})};return{valid:true}};
ArenaEngine.prototype.doDivorce=function(h,a){const r=this.relationships.find(x=>x.id===a.relationId&&x.active&&x.kind==='Династический союз'&&(x.a===h||x.b===h));if(!r||!this.spendInfluence(h,3,'Развод'))throw new Error('Divorce became illegal');r.active=false;r.endedReason='divorce';r.endedRound=this.round;for(const uid of r.characters||[]){for(const house of HOUSES){const c=this.characterByUid(house,uid);if(c)c.spouseOf=null}}this.log('diplomacy',`${h}: развод; союз прекращён`,{house:h,relation:r.id});return{valid:true}};
ArenaEngine.prototype.doReturn=function(h,a){if(this.totalTerritories(h)!==0||!this.spendGold(h,3,'Возвращение из Изгнания'))throw new Error('Return from exile became illegal');const cap=CAPS[h],t=this.territories[cap],owner=t.owner;if(!owner){t.owner=h;t.units[h]=3;return{valid:true}}if(owner===h){t.units[h]=Math.min(num(PARAM.TERRITORY_WARRIOR_CAP,8),num(t.units[h])+3);return{valid:true}}const virtual=`EXILE:${h}`;this.territories[virtual]={id:virtual,type:'WILD',resistance:0,owner:h,fort:false,fortOwner:null,units:{[h]:3}};const out=this.resolvePvp(h,owner,{source:virtual,dest:cap,amount:3},false);delete this.territories[virtual];return out};
ArenaEngine.prototype.freeProcedures=function(h){if(!h||!this.houses[h])return[];const hs=this.houses[h],out=[];for(const r of this.relationships.filter(r=>r.active&&(r.kind==='Официальный Пакт'||r.kind==='Династический союз')&&(r.a===h||r.b===h))){const cost=r.kind==='Официальный Пакт'?2+(h==='Варкайр'?1:0):3;if(hs.influence>=cost)out.push({id:`BREAK:${r.id}`,type:'break',label:`Разорвать ${r.kind}`,relationId:r.id,cost,legal:true})}for(const r of this.relationships.filter(r=>r.active&&(r.kind==='Официальный Пакт'||r.kind==='Династический союз')&&(r.a===h||r.b===h))){const other=r.a===h?r.b:r.a,limit=Math.min(3-num(hs.roundFlags.goldGiven),3-num(this.houses[other].roundFlags.goldReceived),hs.gold);if(limit>0)out.push({id:`GOLD:${other}:${limit}`,type:'goldTransfer',label:`Передать ${limit} золота: ${other}`,other,amount:limit,legal:true})}return out};
ArenaEngine.prototype.applyFreeProcedure=function(h,p){if(p.type==='break'){const r=this.relationships.find(x=>x.id===p.relationId&&x.active);if(!r||!this.spendInfluence(h,p.cost,'Разрыв отношения'))return{valid:false};r.active=false;r.endedReason='break';r.endedRound=this.round;return{valid:true}}if(p.type==='goldTransfer'){const n=Math.trunc(num(p.amount)),to=p.other,hs=this.houses[h],ts=this.houses[to];if(n<1||n>3-num(hs.roundFlags.goldGiven)||n>3-num(ts.roundFlags.goldReceived)||hs.gold<n||!this.relationBetween(h,to,['Официальный Пакт','Династический союз']))return{valid:false};hs.gold-=n;ts.gold+=n;hs.roundFlags.goldGiven=num(hs.roundFlags.goldGiven)+n;ts.roundFlags.goldReceived=num(ts.roundFlags.goldReceived)+n;this.log('diplomacy',`${h} передаёт ${n} золота ${to}`,{house:h,to,amount:n});return{valid:true}}return{valid:false}};
const _startRound=ArenaEngine.prototype.startRound;
ArenaEngine.prototype.startRound=function(){const r=_startRound.call(this);for(const h of HOUSES){this.houses[h].roundFlags.goldGiven=0;this.houses[h].roundFlags.goldReceived=0}return r};
const _incomePhase=ArenaEngine.prototype.incomePhase;
ArenaEngine.prototype.incomePhase=function(){for(const h of HOUSES)if(this.totalTerritories(h)===0){const row=this.economyRow('EXILE'),x=this.parseIncome(row?.['Доход владельца']);this.houses[h].gold+=x.gold;this.houses[h].influence+=x.influence;this.log('income',`${h}: Изгнание +${x.gold} золота, +${x.influence} Влияния`,{house:h,gold:x.gold,influence:x.influence,exile:true})}return _incomePhase.call(this)};
const _spendInfluence=ArenaEngine.prototype.spendInfluence;
ArenaEngine.prototype.spendInfluence=function(h,n,reason){const ok=_spendInfluence.call(this,h,n,reason);if(ok)this.checkPowerAchievements(h);return ok};

// Current-source rules/AI parity patches.
ArenaEngine.prototype.landPaths=function(h,source){
 const out=[],q=[[source,[source]]],best=new Map([[source,0]]);
 while(q.length){const [cur,path]=q.shift(),d=path.length-1;if(d>=2)continue;for(const nx of this.land[cur]||[]){if(path.includes(nx))continue;const t=this.territories[nx],owner=t.owner,np=[...path,nx],nd=d+1;if(owner===h||(owner&&this.hasAccess(h,owner))){out.push(np);if(nd<2&&(best.get(nx)==null||best.get(nx)>nd)){best.set(nx,nd);q.push([nx,np])}}else out.push(np)}}
 return out
};
const _beginOwnActionCurrent=ArenaEngine.prototype.beginOwnAction;
ArenaEngine.prototype.beginOwnAction=function(h){const hs=this.houses[h];if(hs)hs.retreatSeries=null;const out=_beginOwnActionCurrent.call(this,h);this.runAIFreeProcedures(h);return out};
ArenaEngine.prototype.futureActionSlots=function(h){const hs=this.houses[h];const current=this.currentHouse()===h?1:0;return Math.max(0,3-hs.turnsTaken-hs.reserved-current)};
ArenaEngine.prototype.executePrisoner=function(owner,c,captor){const h=this.houses[captor];if(h.influence<3||this.futureActionSlots(captor)<=0)return{valid:false,detail:'Казнь недоступна: требуется 1 будущий слот действия и 3 Влияния'};h.reserved++;this.spendInfluence(captor,3,'Казнь пленника');this.logPrisoner('execute',owner,c,captor,{detail:`${captor} казнит ${c.name} (${owner}); зарезервировано 1 действие, потеряно 3 Влияния`});this.metrics.total.executions++;this.killCharacter(owner,c,'казнь в плену');return{valid:true}};
ArenaEngine.prototype.incomePhase=function(){for(const h of HOUSES){let gold=0,influence=0;if(this.totalTerritories(h)===0){const x=this.parseIncome(this.economyRow('EXILE')?.['Доход владельца']);gold=x.gold;influence=x.influence}else{for(const t of Object.values(this.territories))if(t.owner===h){const x=this.incomeFor(t.id,h);gold+=x.gold;influence+=x.influence}for(let i=1;i<=5;i++){const a=`S0${i}-A`,b=`S0${i}-B`;if(this.territories[a]?.owner===h&&this.territories[b]?.owner===h){const x=this.parseIncome(this.economyRow(`S0${i}`)?.['Доход владельца']);gold+=x.gold;influence+=x.influence}}}gold=Math.max(0,gold+num(this.stateFlags.incomeGoldMod));this.houses[h].gold+=gold;this.houses[h].influence=Math.max(0,this.houses[h].influence+influence);this.log('income',`${h}: +${gold} золота, +${influence} Влияния`,{house:h,gold,influence,exile:this.totalTerritories(h)===0})}};
ArenaEngine.prototype.retreatDestination=function(h,from,count){for(const id of (this.land[from]||[]).slice().sort()){const t=this.territories[id];if(t?.owner===h&&num(t.units[h])+count<=num(PARAM.TERRITORY_WARRIOR_CAP,8))return id}return null};
const _resolvePvpCurrent=ArenaEngine.prototype.resolvePvp;
ArenaEngine.prototype.resolvePvp=function(attacker,defender,a,raid){if(!raid){const t=this.territories[a.dest],s=this.territories[a.source],defenders=num(t?.units[defender]),amount=Math.min(a.amount,num(s?.units[attacker])),hs=this.houses[defender],series=num(hs.retreatSeries?.count),loss=series+1,survivors=defenders-loss,dest=this.retreatDestination(defender,a.dest,survivors);const defendCommander=this.commanderAt(defender,a.dest);const attackPressure=amount+num(this.commanderAt(attacker,a.source)?.attack);const defendPressure=defenders+this.baseDefense(t)+num(defendCommander?.defense);if(series<2&&survivors>=1&&dest&&attackPressure>=defendPressure+2){t.units[defender]=0;this.territories[dest].units[defender]=num(this.territories[dest].units[defender])+survivors;hs.retreatSeries={count:series+1,location:dest};if(defendCommander)defendCommander.armyLocation=dest;s.units[attacker]-=amount;t.owner=attacker;t.units[attacker]=num(t.units[attacker])+amount;this.moveCommanderWithArmy(attacker,a.source,a.dest);this.onCaptureTerritory(attacker,defender,t);this.log('retreat',`${defender} отступает из ${a.dest} в ${dest}; потеря ${loss}`,{house:defender,from:a.dest,to:dest,loss,series:series+1});return{valid:true,retreat:true}}}return _resolvePvpCurrent.call(this,attacker,defender,a,raid)};
ArenaEngine.prototype.canReachHouseNow=function(h,other){for(const source of this.ownedUnitLocations(h)){const q=[[source,0]],seen=new Set([source]);while(q.length){const[cur,d]=q.shift();if(d>=2)continue;const links=[...(this.land[cur]||[]),...(d===0&&PORTS.has(cur)?this.sea[cur]||[]:[])];for(const nx of links){if(seen.has(nx))continue;seen.add(nx);const t=this.territories[nx];if(t?.owner===other)return true;if(t?.owner===h||(t?.owner&&this.hasAccess(h,t.owner)))q.push([nx,d+1])}}}return false};
const _legalActionsCurrent=ArenaEngine.prototype.legalActions;
ArenaEngine.prototype.legalActions=function(h){const out=_legalActionsCurrent.call(this,h),broken=this.houses[h]?.roundFlags?.brokenPartners||[];for(const a of out){if(a.type==='pact'){a.baseScore=Math.max(num(a.baseScore),5);if(broken.includes(a.other))a.baseScore=-50;const hi=HOUSES.indexOf(h),oi=HOUSES.indexOf(a.other);a.scoreComponents={...(a.scoreComponents||{}),partnerTie:((oi-hi+HOUSES.length)%HOUSES.length)*0.01}}if(a.type==='access')a.baseScore=Math.max(num(a.baseScore),3);if(a.type==='fort')a.baseScore=Math.max(num(a.baseScore),5.5);if(a.type==='adviser')a.baseScore=Math.max(num(a.baseScore),4)}return out};
const _applyFreeProcedureCurrent=ArenaEngine.prototype.applyFreeProcedure;
ArenaEngine.prototype.applyFreeProcedure=function(h,p){const rel=p.type==='break'?this.relationships.find(x=>x.id===p.relationId&&x.active):null,other=rel?(rel.a===h?rel.b:rel.a):null;const out=_applyFreeProcedureCurrent.call(this,h,p);if(out?.valid&&other){const arr=this.houses[h].roundFlags.brokenPartners??=[];if(!arr.includes(other))arr.push(other)}return out};
ArenaEngine.prototype.runAIFreeProcedures=function(h){const hs=this.houses[h];if(!hs||hs._freeProcRoundAction===`${this.round}:${hs.turnsTaken}`)return;hs._freeProcRoundAction=`${this.round}:${hs.turnsTaken}`;if(this.round>=4){for(const p of this.freeProcedures(h).filter(p=>p.type==='break')){const r=this.relationships.find(x=>x.id===p.relationId&&x.active),other=r?(r.a===h?r.b:r.a):null;if(other&&this.canReachHouseNow(h,other)){this.applyFreeProcedure(h,p);return}}}for(const p of this.freeProcedures(h).filter(p=>p.type==='goldTransfer')){if(hs.gold>=14&&this.houses[p.other].gold<=3){this.applyFreeProcedure(h,{...p,amount:Math.min(2,p.amount)});return}}};

window.ArenaEngine=ArenaEngine;
window.ARENA_V572_CURRENT={sourceRuntime:true,sourceBlockedActions:['ACT-DRAW','ACT-INTRIGUE','ACT-INVEST']};
window.arenaEngine=new ArenaEngine(DATA);

})();
