#!/usr/bin/env node
'use strict';
const fs=require('fs');const path=require('path');const crypto=require('crypto');
const ROOT=path.resolve(__dirname,'..');const readJSON=p=>JSON.parse(fs.readFileSync(path.join(ROOT,p),'utf8'));
const mgd=readJSON('data/master_game_data_v5.7.2-dev.json'),topo=readJSON('map/canonical_topology_v5.7.2.json'),meta=readJSON('map/territory_metadata_v5.7.2.json'),ai=readJSON('ai/config/canonical_v5.7.2.json'),intrigueModule=readJSON('data/intrigues_v5.7.2.json'),sheets=mgd.sheets;
if(!Array.isArray(intrigueModule.cards)||intrigueModule.cards.length!==40)throw new Error('Canonical Intrigues module must contain exactly 40 cards');
const param=Object.fromEntries(sheets['Global Parameters'].map(r=>[r.PARAM_ID,r['По умолчанию']]));const typeCode={'Столица':'CAPITAL','Город':'CITY','Деревня':'VILLAGE','Дикая земля':'WILD','Половина центрального острова':'ISLAND_HALF'};
const territoryMeta=meta.territories.map(r=>({id:r.id,name:r.name,house_sector:r.house_sector,type:typeCode[r.type],resistance:r.resistance,legacy_arena_id:r.legacy_arena_id,icon:r.icon}));if(territoryMeta.some(r=>!r.type))throw new Error('Unknown territory type in metadata');
const houses=sheets.Houses.map(r=>({name:r['Дом'],ruler:r['Правитель'],ability:r['Способность'],weakness:r['Слабость']})),events=sheets.Events.map(r=>({id:r.CARD_ID,name:r['Название'],...r}));
const data={game:'Жестокий Век',version:'V5.7.2-PLAYABLE-CURRENT-DEV',sourceVersion:mgd.version,params:param,actions:sheets.Actions,economy:sheets.Economy,houses,characters:sheets.Characters,advisors:sheets.Advisors,ambitions:sheets.Ambitions,events,intrigues:intrigueModule.cards,intrigueSystem:intrigueModule.system,aiConfig:ai,map:{territories:topo.territories,capitals:topo.capitals,ports:topo.ports,land_edges:topo.land_edges,sea_edges:topo.sea_edges,territoryMeta},sourceBlockedActions:[]};
const read=p=>fs.readFileSync(path.join(ROOT,p),'utf8');const aiAdapter=read('arena/source/current/ai_adapter.js'),prefix=read('arena/source/current/recovery/engine_runtime_recovered_prefix.js'),tail=[0,1,2].map(i=>read(`arena/source/current/engine_runtime_tail.part-0${i}.js`)).join(''),engine=prefix+tail,parity=read('arena/source/current/current_parity_patch.js'),physical=read('arena/source/current/physical_components_patch.js'),intrigue=read('arena/source/current/intrigue_runtime_patch.js'),ui=read('arena/source/current/ui_runtime.js');
const prisonerLabels=['Отпустить пленника','Взять в плен','Требовать выкуп N','Казнить'];
const html=`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Жестокий Век — Arena V5.7.2 current dev</title></head><body><main><h1>Жестокий Век — Arena V5.7.2 current dev</h1><p>Prisoner choices: ${prisonerLabels.join(' / ')}.</p></main><script>window.ARENA_DATA=${JSON.stringify(data)};</script><script>${aiAdapter}\n${engine}</script><script>${parity}</script><script>${physical}</script><script>${intrigue}</script><script>${ui}</script></body></html>\n`;
const outDir=path.join(ROOT,'arena/builds');fs.mkdirSync(outDir,{recursive:true});const out=path.join(outDir,'V5.7.2_PLAYABLE_CURRENT_DEV.html');fs.writeFileSync(out,html);const hash=crypto.createHash('sha256').update(html).digest('hex');
const adviserCopies=(sheets.Advisors||[]).reduce((s,r)=>s+Math.max(1,Number(r['Копий']||2)),0);const manifest={game:data.game,version:data.version,sourceVersion:data.sourceVersion,sha256:hash,bytes:Buffer.byteLength(html),sourceBlockedActions:[],territories:topo.territories.length,actionsInMGD:sheets.Actions.length,intrigueCards:intrigueModule.cards.length,physicalCardCopies:120+intrigueModule.cards.reduce((s,c)=>s+Math.max(1,Number(c['Копий']||1)),0),advisorPhysicalCopies:adviserCopies,advisorMarketSize:4,ambitionPhysicalDeal:true,uiPanels:['MAP','HOUSES','DIPLOMACY','JOURNAL','GAME_MASTER'],humanActionSelection:true,humanPrisonerChoice:true,builtAtPolicy:'deterministic tracked-source build'};fs.writeFileSync(path.join(outDir,'V5.7.2_PLAYABLE_CURRENT_DEV.manifest.json'),JSON.stringify(manifest,null,2)+'\n');console.log(JSON.stringify(manifest,null,2));
