#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path');
const ROOT=path.resolve(__dirname,'..'),src=path.join(ROOT,'data','intrigues_v5.7.2.json'),outDir=path.join(ROOT,'cards','generated');
const mod=JSON.parse(fs.readFileSync(src,'utf8'));if(!Array.isArray(mod.cards)||mod.cards.length!==40)throw new Error('Expected 40 Intrigues');fs.mkdirSync(outDir,{recursive:true});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cards=mod.cards.map(c=>`<article class="card"><div class="id">${esc(c.CARD_ID)}</div><h2>${esc(c['Название'])}</h2><div class="meta">Активная Интрига · ${c['Цена_золота']} зол. · проверка ${c['Сложность']}+</div><p>${esc(c['Текст'])}</p><footer>След: до конца следующего раунда · доказательство: -${c['Штраф_доказательства_Влияние']} Влияния виновнику</footer></article>`).join('\n');
const html=`<!doctype html><html lang="ru"><head><meta charset="utf-8"><title>Жестокий Век — Интриги V5.7.2</title><style>@page{size:A4;margin:8mm}*{box-sizing:border-box}body{margin:0;font:10pt Georgia,serif;color:#1c1711}.sheet{display:grid;grid-template-columns:repeat(3,63mm);grid-auto-rows:88mm;gap:3mm;justify-content:center}.card{border:1px solid #251d14;border-radius:3mm;padding:4mm;position:relative;break-inside:avoid;overflow:hidden}.id{position:absolute;right:3mm;top:2mm;font:8pt monospace}h2{font-size:14pt;margin:1mm 0 3mm;padding-right:13mm}.meta{font-weight:bold;border-bottom:1px solid #777;padding-bottom:2mm;margin-bottom:3mm}p{line-height:1.25}footer{position:absolute;left:4mm;right:4mm;bottom:4mm;font-size:8.5pt;border-top:1px solid #aaa;padding-top:2mm}@media screen{body{background:#ddd;padding:8mm}.sheet{background:white;padding:8mm;width:max-content;margin:auto}}</style></head><body><main class="sheet">${cards}</main></body></html>\n`;
const out=path.join(outDir,'Zhestokiy_Vek_Intrigues_V5.7.2_40.html');fs.writeFileSync(out,html,'utf8');console.log(`Generated ${path.relative(ROOT,out)}: ${mod.cards.length} cards`);
