#!/usr/bin/env node
"use strict";
const fs=require('fs'),path=require('path');
const ROOT=path.resolve(__dirname,'..');
const INPUT=path.join(ROOT,'data','master_game_data_v5.7.2-dev.json');
const INTRIGUES=path.join(ROOT,'data','intrigues_v5.7.2.json');
const OUTPUT=path.join(ROOT,'cards','canonical_registry_v5.7.2.json');
const COMPOSITE=path.join(ROOT,'cards','canonical_card_set_v5.7.2.json');
const PHYSICAL_CARD_SHEETS=new Set(['Events','Houses','Characters','Advisors','Ambitions','Intrigues']);
const ID_KEYS=['CARD_ID','AMBITION_ID','CHARACTER_ID','HOUSE_ID','ID'];
function invariant(c,m){if(!c)throw new Error(m)}
function stable(v){return JSON.stringify(v,null,2)+'\n'}
function buildBase(mgd){const groups={},namespacedIds=new Set(),globalCardIds=new Map();let total=0;for(const[sheet,rows]of Object.entries(mgd.sheets||{})){if(!Array.isArray(rows)||!PHYSICAL_CARD_SHEETS.has(sheet))continue;const selected=rows.filter(r=>r&&typeof r==='object');if(!selected.length)continue;groups[sheet]=selected;total+=selected.length;selected.forEach((row,index)=>{const key=ID_KEYS.find(k=>row[k]!=null&&row[k]!=='');if(key){const id=String(row[key]);namespacedIds.add(`${sheet}:${key}:${id}`);if(key==='CARD_ID'){const prior=globalCardIds.get(id);invariant(!prior||prior===sheet,`Duplicate CARD_ID ${id}`);globalCardIds.set(id,sheet)}}else namespacedIds.add(`${sheet}:ROW:${index}`)});}return{game:'Жестокий Век',version:mgd.version||'V5.7.2-DEV',status:'GENERATED_CANONICAL_CARD_REGISTRY',source:'data/master_game_data_v5.7.2-dev.json',policy:'Generated verbatim from active MGD physical card-design sheets. Internal ROW identities are registry-only and are not gameplay IDs. This registry does not substitute for missing card sources such as an absent Intrigues sheet or for print art masters.',object_count:total,namespaced_id_count:namespacedIds.size,unique_card_id_count:globalCardIds.size,sheets:groups}}
function main(){const mgd=JSON.parse(fs.readFileSync(INPUT,'utf8')),intr=JSON.parse(fs.readFileSync(INTRIGUES,'utf8'));invariant(Array.isArray(intr.cards)&&intr.cards.length===40,'Intrigues module must contain exactly 40 designs');const ids=new Set();for(const c of intr.cards){invariant(/^INT-\d{2}$/.test(String(c.CARD_ID)),`Bad Intrigue CARD_ID ${c.CARD_ID}`);invariant(!ids.has(c.CARD_ID),`Duplicate Intrigue ${c.CARD_ID}`);ids.add(c.CARD_ID);invariant(Number.isInteger(c['Цена_золота'])&&c['Цена_золота']>=0,'Intrigue cost invalid');invariant(Number.isInteger(c['Сложность'])&&c['Сложность']>=2,'Intrigue difficulty invalid')}
 const base=buildBase(mgd),intrCopies=intr.cards.reduce((s,c)=>s+Math.max(1,Number(c['Копий']||1)),0),advisorRows=mgd.sheets?.Advisors||[],advisorExtra=advisorRows.reduce((s,r)=>s+Math.max(0,Number(r['Копий']||1)-1),0),basePhysicalCopies=base.object_count+advisorExtra;const composite={game:'Жестокий Век',version:mgd.version||'V5.7.2-DEV',status:'COMPOSITE_CANONICAL_CARD_SET',design_count:base.object_count+intr.cards.length,physical_copy_count:basePhysicalCopies+intrCopies,modules:[{source:'cards/canonical_registry_v5.7.2.json',designs:base.object_count,physical_copies:basePhysicalCopies},{source:'data/intrigues_v5.7.2.json',designs:intr.cards.length,physical_copies:intrCopies,status:intr.status}],policy:'The complete physical card set is the union of the generated MGD base registry and explicit canonical card modules.'};
 if(process.argv.includes('--check')){const current=fs.existsSync(OUTPUT)?fs.readFileSync(OUTPUT,'utf8'):'';invariant(current===stable(base),'cards/canonical_registry_v5.7.2.json is stale; regenerate it');const cc=fs.existsSync(COMPOSITE)?fs.readFileSync(COMPOSITE,'utf8'):'';invariant(cc===stable(composite),'cards/canonical_card_set_v5.7.2.json is stale; regenerate it');console.log(`Card registry check OK: ${composite.design_count} designs / ${composite.physical_copy_count} physical cards`);return}
 fs.writeFileSync(OUTPUT,stable(base),'utf8');fs.writeFileSync(COMPOSITE,stable(composite),'utf8');console.log(`Generated composite card set: ${composite.design_count} designs / ${composite.physical_copy_count} physical cards`)}
main();
